exp_base: ckpt/blender/trex_softplus
random_seed: 0

# Logging
wandb:
  project: dnerf_blender_trex
  name: shifted_softplus

# Data
dataset_type: blender
dataset_name: trex
data_root: /media/SSD/ziyang/Datasets_NeRF/nerf_dataset/dnerf/trex

# Fourier embedding
n_freq_point: 10
n_freq_view: 4
n_freq_time: 10

# MLP
n_layer: 8
n_dim: 256
use_viewdir: True
rgb_act: sigmoid
density_act: shifted_softplus

two_model_for_fine: False
train_on_coarse: False
zero_canonical: True

# Ray & point sampling
use_batching: False
use_ndc: False
n_sample_ray: 500
n_sample_point: 64
n_sample_point_fine: 128
perturb: True
density_noise_std: 0.0

# Rendering
no_batching: True
white_bkgd: True

# Training
n_iters: 800000
lrate: 0.0005
lrate_decay: 0.1
lrate_decay_step: 500000

precrop_iters: 500
precrop_iters_time: 100000
precrop_frac: 0.5

val_freq: 2000
save_freq: 1000

chunk_ray: 4096
chunk_point: 1000000
half_res: True